[tool.poetry]
name = "gpt-terminal-chat"
version = "0.1.0"
description = ""
authors = ["alejoboga-ai <alejo@zelta.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.0.354"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
